name: Actualizar CER

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-cer:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: python update_cer.py

      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add indices/cer.json
          git diff --cached --exit-code || (
            git commit -m "Actualiza CER index"
            git push origin main
          )
