name: Actualizar CER

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-cer:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          & 'C:\Program Files\Python313\python.exe' -m pip install requests beautifulsoup4

      - name: Run update & push via API
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          & 'C:\Program Files\Python313\python.exe' update_cer.py

